# Generated by Django 4.1.1 on 2022-10-15 13:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='account_info',
            fields=[
                ('account_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('account_email', models.EmailField(max_length=254)),
                ('account_order', models.DateField(default=datetime.datetime(2022, 10, 15, 21, 36, 14, 61033))),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
