# Generated by Django 4.1.2 on 2022-10-12 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_info',
            name='account_order',
            field=models.DateField(default=datetime.datetime(2022, 10, 12, 18, 31, 46, 289731)),
        ),
    ]
