# Generated by Django 4.1.1 on 2022-10-15 13:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Django_app', '0003_alter_account_info_account_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_info',
            name='account_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='account_order',
            field=models.DateField(default=datetime.datetime(2022, 10, 15, 21, 50, 4, 616370)),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
