# Generated by Django 4.1.2 on 2022-10-13 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_app', '0003_alter_account_info_account_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_info',
            name='id',
        ),
        migrations.AlterField(
            model_name='account_info',
            name='account_name',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='account_order',
            field=models.DateField(default=datetime.datetime(2022, 10, 13, 21, 30, 30, 68938)),
        ),
    ]
